# Change these first
owner: Delegation-numerique-en-sante  # Your GitHub username
repo: mesconseilscovid-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: MCC
    url: https://mesconseilscovid.sante.gouv.fr

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /mesconseilscovid-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MCC Upptime
  introTitle: "Disponibilité du site MesConseilsCovid."
  introMessage: Uptime status for [https://mesconseilscovid.sante.gouv.fr](https://mesconseilscovid.sante.gouv.fr)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
